test_case_3 = '''
1. Background & Problem Motivation  
Shock-wave/boundary-layer interactions are a critical phenomenon in supersonic and hypersonic vehicle design, causing localized peaks in heat transfer and pressure loads that can lead to structural failure. When an incoming turbulent boundary layer encounters an oblique shock generated by a surface deflection (like a compression ramp), it can separate, forming a complex, unsteady flow structure. Accurately predicting the size of the separation region and the associated surface heating is a major challenge for computational fluid dynamics (CFD). This task involves simulating a canonical 2D compression ramp interaction to validate turbulence models and numerical methods against experimental data.

2. Problem Specification  
Your task is to plan a numerical simulation strategy to study a turbulent SBLI on a compression ramp and validate the results against provided experimental skin friction data.

**Governing Equations**:  
The flow is governed by the 2D/3D, unsteady, compressible Navier-Stokes equations, often coupled with a turbulence model. For a Reynolds-Averaged Navier-Stokes (RANS) approach, the equations are:

\\[
\\frac{\\partial \\overline{Q}}{\\partial t} + \\frac{\\partial \\overline{F}}{\\partial x} + \\frac{\\partial \\overline{G}}{\\partial y} = \\frac{1}{Re} \\left( \\frac{\\partial \\overline{F}_v}{\\partial x} + \\frac{\\partial \\overline{G}_v}{\\partial y} \\right) + S_{turb}
\\]

where \\( \\overline{Q} \\) contains the mean flow variables, and \\( S_{turb} \\) represents the source terms from the chosen turbulence model (e.g., Spalart-Allmaras (SA) or Menter's SST).

**Geometry**:  
A flat plate followed by a compression ramp. The ramp angle is a key parameter (e.g., \\( 15^\\circ \\), \\( 24^\\circ \\), or \\( 34^\\circ \\) as found in classic studies). The inflow is positioned upstream to allow a fully developed turbulent boundary layer to form before the ramp.

**Flow Conditions**:
- Freestream Mach number: \\( M_\\infty = 5.0 \\)  
- Reynolds number based on momentum thickness at the ramp corner: \\( Re_\\theta \\sim \\mathcal{O}(10^4) \\)  
- Incoming boundary layer state: Fully turbulent  
- Wall condition: Isothermal or adiabatic, based on reference data

**Primary Objective**:  
To accurately predict the interaction footprint. Key validation metrics include:

- The streamwise distribution of the skin friction coefficient (\\( C_f \\)) on the ramp surface, capturing the separation zone (where \\( C_f < 0 \\)) and the reattachment point  
- The wall pressure distribution  
- The size and structure of the separation bubble

3. Computational Domain & Boundary Conditions  

**Domain**:  
A structured, quad-dominant mesh. The domain must extend sufficiently upstream of the ramp corner to develop the inflow boundary layer and downstream to capture re-establishing flow. Significant grid clustering is required in the boundary layer (\\( y^+ < 1 \\) for wall-resolved simulations) and in the anticipated shock and separation regions.

**Boundary Conditions**:
- **Inflow**: Supersonic inflow with prescribed turbulent boundary layer profiles (from a separate simulation or empirical correlations)  
- **Ramp and Upstream Plate Surface**: No-slip, isothermal or adiabatic wall  
- **Top Boundary**: Freestream or characteristic-based boundary condition placed high enough to not interfere with the shock system  
- **Outflow**: Supersonic outflow (extrapolation)

4. Task Requirements & Deliverables  
Do not write the actual code. Your task is to produce a **CFD Solution Strategy Document** that outlines the numerical approach. This document must address:

- **Turbulence Modeling Strategy**: Justify the choice of turbulence model (e.g., RANS SA or SST, DES, LES). Discuss the limitations of standard RANS models for this flow and whether compressibility corrections are necessary.

- **Spatial Discretization & Shock Capturing**: Specify the numerical scheme for convective fluxes. A high-resolution shock-capturing scheme (e.g., Roe, AUSM+ with MUSCL reconstruction) is mandatory. Justify the choice of limiter to balance stability and accuracy.

- **Mesh Design Strategy**: Detail the mesh refinement strategy. Specify target cell counts in key regions, citing the need for grid convergence studies (e.g., from "coarse" 37k to "fine" 146k quadrilateral elements). Explain how you would ensure \\( y^+ \\) requirements are met.

- **Solution Strategy & Validation**: Describe the solution initialization (e.g., starting from freestream, using a coarser grid solution). Define the specific validation procedure, listing the exact experimental data (skin friction, pressure) you would compare against and the error metrics you would compute.
'''
